language: node_js
node_js:
  - '10'

# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
  chrome: stable
  apt:
    packages:
    - libgconf-2-4

## Cache NPM folder and Cypress binary
## to avoid downloading Cypress again and again
cache:
  directories:
    - ~/.npm
    - ~/.cache

before_install:
  - npm install -g grunt-cli

install:
  # use the new "ci" command for fastest installs on CI
  - npm ci

before_script:
  - grunt build
  
script: 
  - grunt transpile
  - grunt jasmine
  - npm run start:ci &
  - npm run cy:run:chrome