name: "New Spreadsheet Layer"
on:
  issue_comment:
    types: [created, edited]
  issues:
    types: [opened]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout and install dependencies
        run: npm install @actions/core @actions/github marked

      - name: Generate New Spreadsheet Layer
        run: node ./scripts/actionGenLayer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
