version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: esri-leaflet
    versions:
    - 3.0.0
  - dependency-name: "@babel/plugin-transform-for-of"
    versions:
    - 7.12.1
    - 7.12.13
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: grunt-contrib-uglify
    versions:
    - 5.0.0
  - dependency-name: stringstream
    versions:
    - 0.0.6
